version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    volumes:
      - "../nginx:/etc/nginx/conf.d"
    #   - "./etc/ssl:etc/ssl"
      - "../sites:/var/www/sites"
    ports:
      - "8080:80"
    restart: always

  php-fpm:
    container_name: php-fpm
    image: nanoninja/php-fpm:7.1.14
    volumes:
      - "../php/php.ini:/usr/local/etc/php/conf.d/php.ini"
      - "../sites:/var/www/sites"
    ports:
      - "9000:9000"
    restart: always
  mysql:
    container_name: mysql
    image: mysql:5.7
    ports:
      - 3306:3306
    volumes:
      - ../mysql/data:/var/lib/mysql/
#      - /etc/localtime:/etc/localtime:ro
#      - ./mysql/conf.d/:/etc/mysql/conf.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
  redis:
    container_name: redis
    image: redis
    volumes:
      - ../redis/data:/data/
#      - /etc/localtime:/etc/localtime:ro
    ports:
      - 6379:6379
